version: '3.9'
services:
  #database section
  sqlserverdb:
    container_name: sqlservicedb
    environment:
      SA_PASSWORD: "PassWOrd!"
      ACCEPT_EULA: "Y"
    restart: always
    volumes:
      - sqlserver_data:/var/lib/sqlserver/data
    ports:
      - "1435:1433"
    
  
    
